#!/usr/bin/env python3
"""Update the generated public-repository index in the profile README."""

from __future__ import annotations

import json
import os
from pathlib import Path
from urllib.request import Request, urlopen


OWNER = os.environ.get("PORTFOLIO_OWNER", "georgypevchikh")
ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
START = "<!-- PUBLIC-REPOS:START -->"
END = "<!-- PUBLIC-REPOS:END -->"
FEATURED_ORDER = {
    "restamenu-console-demo": 0,
    "stuff-sycle-case-study": 1,
}


def github_repositories() -> list[dict]:
    request = Request(
        f"https://api.github.com/users/{OWNER}/repos?type=owner&sort=updated&per_page=100",
        headers={
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": f"{OWNER}-profile-sync",
        },
    )
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")

    with urlopen(request, timeout=30) as response:
        repositories = json.load(response)

    return [
        repo
        for repo in repositories
        if not repo["private"]
        and not repo["fork"]
        and not repo["archived"]
        and repo["name"].lower() != OWNER.lower()
    ]


def escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def repository_row(repo: dict) -> str:
    name = repo["name"]
    description = repo.get("description") or "Public project repository."
    topics = [topic.replace("-", " ") for topic in repo.get("topics", [])[:4]]
    technology = " · ".join(filter(None, [repo.get("language"), *topics])) or "Documentation"
    homepage = repo.get("homepage")
    links = f"[Repository]({repo['html_url']})"
    if homepage:
        links += f" · [Live]({homepage})"

    return (
        f"| **[{escape_cell(name)}]({repo['html_url']})** "
        f"| {escape_cell(description)} "
        f"| {escape_cell(technology)} "
        f"| {links} |"
    )


def generated_block(repositories: list[dict]) -> str:
    repositories.sort(
        key=lambda repo: (
            FEATURED_ORDER.get(repo["name"], 100),
            repo["name"].lower(),
        )
    )
    lines = [
        START,
        "<!-- Generated by scripts/update_public_projects.py. Do not edit this block manually. -->",
        "| Repository | What it demonstrates | Stack / topics | Links |",
        "|---|---|---|---|",
        *(repository_row(repo) for repo in repositories),
        END,
    ]
    return "\n".join(lines)


def main() -> None:
    current = README.read_text()
    if START not in current or END not in current:
        raise RuntimeError("README is missing generated-section markers")

    prefix, remainder = current.split(START, 1)
    _, suffix = remainder.split(END, 1)
    updated = prefix + generated_block(github_repositories()) + suffix
    README.write_text(updated)


if __name__ == "__main__":
    main()
